name: intercom_flutter
description: Flutter plugin for Intercom integration. Provides in-app messaging
  and help-center Intercom services
version: 3.1.5
homepage: https://github.com/gabdsg/intercom_flutter

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.gabdsg.intercom
    pluginClass: IntercomFlutterPlugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.7 <2.0.0"
